# --- Parámetros --- 

# Host
@host=http://127.0.0.1

# Puerto, le paso el valor del puerto en el archivo .env con dotenv
@port={{$dotenv PORT}}

# --- Llamados a la API --- 

### Llamado al endpoint /health
GET {{host}}:{{port}}/health

### Llamado a endpoint inexistente
GET {{host}}:{{port}}/health-v1

### Llamado a la ruta principal
GET {{host}}:{{port}}/

### Llamado a la pokeapi (capa de proxy)
GET {{host}}:{{port}}/proxy/pokemon/pokemon

### Llamado al chat de mi api - Agregar un chat al historial del usuario 1
# "Content-Type: application/json": Define el tipo de contenido a pasarle (en este caso json)
# "{"user": {"userId": "user_1", "prompt": "stub"}}": El cuerpo de la request
POST {{host}}:{{port}}/api/v1/chat
Content-Type: application/json

{
    "user": {"userId": "user_1", "prompt": "stub"}
}

### Llamado al historial del chat del usuario 1
GET {{host}}:{{port}}/api/v1/history
Content-Type: application/json

{
    "user": {"userId": "user_1"}
}

### Borrar un char del historial del usuario 1
DELETE {{host}}:{{port}}/api/v1/history/c2_u1
Content-Type: application/json

{
    "user": {"userId": "user_1"}
}