# --- Parámetros --- 

# Host
@host=http://127.0.0.1

# Puerto, le paso el valor del puerto en el archivo .env con dotenv
@port={{$dotenv PORT}}

# --- Llamados a la API --- 

### Llamado al endpoint /health
GET {{host}}:{{port}}/health

### Llamado a endpoint inexistente
GET {{host}}:{{port}}/health-v1

### Llamado a la ruta principal
GET {{host}}:{{port}}/

### Llamado a la pokeapi (capa de proxy)
GET {{host}}:{{port}}/proxy/pokemon/pokemon

### Llamado al chat mi api
# "Content-Type: application/json": Define el tipo de contenido a pasarle (en este caso json)
# "{"prompt": "stub"}": El cuerpo de la request, envía un prompt con "stub" como contenido
POST {{host}}:{{port}}/api/v1/chat
Content-Type: application/json

{
    "prompt": "stub"
}